### ISSUE TITLE
Footer text colour

### ISSUE THREAD

**Issue by ZeevoX** [ZeevoX/summer-project#10]
![Poor contrast ratio text in the footer](https://user-images.githubusercontent.com/8385172/60342521-9895fd00-99a9-11e9-9480-e003219f60ef.png)

Footer text has a very poor contrast ratio with the background. Please update the colour of the text in the CSS to make this text more accessible and legible

**Comment by LCKMS** [comment]
Yeah I tried with:
a:link {
  color: white;
}
but it didn't do anything

**Comment by ZeevoX** [comment]
the poor contrast ratio occurs if the link has previously been visited, use the following code instead:
``` css
a:visited {
  color: white;
}
```
More information is available on [w3schools](https://www.w3schools.com/css/css_link.asp).
